FROM mcr.microsoft.com/dotnet/sdk:7.0 AS build
WORKDIR "/src"
COPY . .
WORKDIR "/src/IdleWithBlazor.Web"
RUN dotnet restore
RUN dotnet publish "IdleWithBlazor.Web.csproj" -c Release -o /app/publish

FROM nginx:1.23.0-alpine
WORKDIR "/src"
EXPOSE 8080
COPY nginx.conf /etc/nginx/nginx.conf
COPY --from=build /app/publish/wwwroot /user/share/nginx/html